spring:
  application:
    name: feb25-jpa
  datasource:
    url: jdbc:h2:./studentDb
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    show-sql: true

server:
  port: 8095
